name: Template Lint

on:
  push:
    branches: [master, develop]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Jinja2 linter
        run: |
          python -m pip install --upgrade pip
          pip install jinjalint

      - name: Lint Jinja templates
        run: |
          jinjalint {{cookiecutter.project_slug}}/
