name: Template Lint

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Jinja2 CLI
        run: |
          pip install jinja2-cli

      - name: Lint Jinja templates
        run: |
          echo "Linting all template files under {{cookiecutter.project_slug}}..."
          find {{cookiecutter.package_name}} -type f \
            ! -name "*.png" ! -name "*.jpg" ! -name "*.ico" ! -name "*.gif" \
            -print0 | while IFS= read -r -d '' f; do
             # Skip empty or binary files
             if file "$f" | grep -q text; then
               echo "Checking $f"
               jinja2 --strict "$f" cookiecutter.json || exit 1
            fi
          done
